name: Deploy Flutter Web App and Jekyll Site with Submodule Sync

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build Flutter Web App
  build_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are included
          fetch-depth: 0    # Fetch full history to detect changes in submodules

      - name: Check for submodule changes
        id: submodule_check
        run: |
          git submodule update --remote --init --recursive
          if git diff --quiet --exit-code; then
            echo "No changes in submodule."
            echo "skip_flutter_build=true" >> $GITHUB_ENV
          else
            echo "Submodule has changed."
            echo "skip_flutter_build=false" >> $GITHUB_ENV
          fi

      - name: Set up Flutter
        if: env.skip_flutter_build == 'false'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'  # Specify the Flutter version

      - name: Install dependencies
        if: env.skip_flutter_build == 'false'
        run: flutter pub get

      - name: Build Flutter web app
        if: env.skip_flutter_build == 'false'
        run: flutter build web

      - name: Upload Flutter web build artifact
        if: env.skip_flutter_build == 'false'
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: ./build/web

  # Build Jekyll Site
  build_jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Jekyll artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: jekyll-site
        
  # Deploy Job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build_flutter, build_jekyll]
    steps:
      - name: Download Flutter Web Build Artifact
        if: env.skip_flutter_build == 'false'
        uses: actions/download-artifact@v3
        with:
          name: flutter-web-build
          path: ./build/web

      - name: List files in build/web
        if: env.skip_flutter_build == 'false'
        run: ls -R ./build/web

      - name: Deploy Flutter Web App
        if: env.skip_flutter_build == 'false'
        id: flutter_deploy
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

      - name: Download Jekyll Site Artifact
        uses: actions/download-artifact@v3
        with:
          name: jekyll-site
          path: ./_site

      - name: List files in _site
        run: ls -R ./_site

      - name: Deploy Jekyll Site
        id: jekyll_deploy
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - name: Check for errors
        run: |
          if [ -f ./build/web/index.html ]; then
            echo "Flutter deployment successful."
          else
            echo "Flutter deployment failed."
          exit 1
          fi

          if [ -f ./_site/index.html ]; then
            echo "Jekyll deployment successful."
          else
            echo "Jekyll deployment failed."
            exit 1
          fi

  # # Deploy Job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: [build_flutter, build_jekyll]
  #   steps:
  #     - name: Download Flutter Web Build Artifact
  #       if: env.skip_flutter_build == 'false'
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: flutter-web-build
  #         path: ./build/web

  #     - name: Deploy Flutter Web App
  #       if: env.skip_flutter_build == 'false'
  #       id: flutter_deploy
  #       uses: actions/deploy-pages@v4
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./build/web

  #     - name: Deploy Jekyll Site
  #       id: jekyll_deploy
  #       uses: actions/deploy-pages@v4
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./_site

  #     - name: Check for errors
  #       run: |
  #         if [ -f ./web/index.html ]; then
  #           echo "Flutter deployment successful."
  #         else
  #           echo "Flutter deployment failed."
  #           exit 1
  #         fi
          

  #         if [ -f ./_site/index.html ]; then
  #           echo "Jekyll deployment successful."
  #         else
  #           echo "Jekyll deployment failed."
  #           exit 1
  #         fi
