name: Deploy Flutter Web App and Jekyll Site with Submodule Sync

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build Flutter Web App
  build_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are included
          fetch-depth: 0    # Fetch full history to detect changes in submodules

      - name: Check for submodule changes
        id: submodule_check
        run: |
          git submodule update --remote --init --recursive
          if git diff --quiet --exit-code; then
            echo "No changes in submodule."
            echo "skip_flutter_build=true" >> $GITHUB_ENV
          else
            echo "Submodule has changed."
            echo "skip_flutter_build=false" >> $GITHUB_ENV
          fi

      - name: Set up Flutter
        # if: env.skip_flutter_build == 'false'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Install dependencies
        # if: env.skip_flutter_build == 'false'
        run: flutter pub get

      - name: Build Flutter web app
        # if: env.skip_flutter_build == 'false'
        run: flutter build web

      - name: Check for symlinks and size in Flutter web build
        # if: env.skip_flutter_build == 'false'
        run:  |
          find ./build/web -type l
          du -sh ./build/web

      - name: Upload Flutter web build artifact
        # if: env.skip_flutter_build == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          # name: github-pages
          path: ./build/web

  # Build Jekyll Site
  build_jekyll:
    runs-on: ubuntu-latest
    needs: build_flutter #Self Added
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        #with:
         # submodules: true  #Self Added

      # #Self Added
      # - name: Check for submodule changes
      #   id: submodule_check_jekyll
      #   run: |
      #     git submodule update --remote --init --recursive
      #     if git diff --quiet --exit-code; then
      #       echo "No changes in submodule."
      #       echo "submodule_changed=false" >> $GITHUB_ENV
      #     else
      #       echo "Submodule has changed."
      #       echo "submodule_changed=true" >> $GITHUB_ENV
      #     fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        # if: env.submodule_changed == 'true' #Self-Added
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Check for symlinks and size in Jekyll site
        # if: env.submodule_changed == 'true' #Self-Added
        run: |
            find ./_site -type l
            du -sh ./_site

      
      - name: Upload Jekyll artifact
        # if: env.submodule_changed == 'true' #Self-Added
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          # name: github-pages
          path: ./_site
          #Added
          retention-days: 1  # Optional: reduce retention to save space
        #   if-no-files-found: warn
        # continue-on-error: true  # Skip errors, but log warnings

  # Deploy Job
  deploy:
    environment:
      name: git_pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build_flutter, build_jekyll]
    steps:
      - name: List all artifacts before deployment
        run: |
          echo "Available artifacts:"
          ls -R ${{ github.workspace }}
          
      - name: Download Flutter Web Build Artifact
        # if: env.skip_flutter_build == 'false'
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-build
          # name: github-pages
          path: ./build/web

      - name: List files in build/web
        # if: env.skip_flutter_build == 'false'
        run: ls -R ./build/web

      - name: Deploy Flutter Web App
        # if: env.skip_flutter_build == 'false'
        id: flutter_deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # artifact-name: flutter-web-build
          # name: github-pages
          # name: flutter-web-build

      - name: Download Jekyll Site Artifact
        # if: env.submodule_changed == 'true' #SelfAdded
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          # name: github-pages
          path: ./_site

      - name: List files in _site
        run: ls -R ./_site

      - name: Deploy Jekyll Site
        # if: env.submodule_changed == 'true' #SelfAdded
        id: jekyll_deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # artifact_name: jekyll-site
          # name: github-pages
          # name: jekyll-site

      - name: Check for errors
        run: |
          if [ -f ./build/web/index.html ]; then
            echo "Flutter deployment successful."
          else
            echo "Flutter deployment failed."
            exit 1
          fi

          if [ -f ./_site/index.html ]; then
            echo "Jekyll deployment successful."
          else
            echo "Jekyll deployment failed."
            exit 1
          fi
