name: Deploy Flutter Web App and Jekyll Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Update submodules
        run: |
          git submodule update --remote --init --recursive

      - name: Setup Flutter Web App
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Install Dependencies and Build Web App
        run: |
          flutter pub get
          flutter build web

      - name: Build Jekyll Site
        uses: actions/configure-pages@v5

      - name: Install Dependencies and Build Jekyll
        run: |
          bundle install
          bundle exec jekyll build

      - name: Upload Flutter Web App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: build/web

      - name: Upload Jekyll Site Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - name: Download Flutter Web App Artifact
        uses: actions/download-artifact@v4
        with:
          name: flutter-web
          path: ./flutter-web

      - name: Download Jekyll Site Artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: ./jekyll-site

      - name: Deploy Flutter Web App
        id: deploy_flutter
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: flutter-web

      - name: Deploy Jekyll Site
        id: deploy_jekyll
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: jekyll-site

      - name: Check deployment
        run: |
          if [ -f ./flutter-web/index.html ]; then
            echo "Flutter deployment successful."
          else
            echo "Flutter deployment failed."
            exit 1
          fi

          if [ -f ./jekyll-site/index.html ]; then
            echo "Jekyll deployment successful."
          else
            echo "Jekyll deployment failed."
            exit 1
          fi
